# Generated by Django 4.1 on 2022-08-15 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='summary',
            field=models.CharField(editable=False, max_length=25, verbose_name='Resumo'),
        ),
    ]
