# Generated by Django 4.1 on 2022-08-15 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_posts_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='summary',
        ),
    ]
