# Generated by Django 4.1 on 2022-08-21 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_posts_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Criado em'),
        ),
    ]
